### ISSUE TITLE
Game continues on even if a player wins

### ISSUE THREAD

**Issue by mertaytore** [barispoyraz/TRONGame#2]
### Current Behavior
Player 2 crashes into Player 1 for the first time and the game continues. Same behavior was observed vice versa.

### Expected Behavior
After the collision, the winner should be declared as Player 1 and the game is expected to end. 

<img width="840" alt="screen shot 2017-08-11 at 4 40 02 pm" src="https://user-images.githubusercontent.com/10900008/29215473-c8790aa2-7eb3-11e7-90f4-539adc9d162d.png">

**Comment by barispoyraz** [comment]
Thank you for pointing out this issue. I solved it by replacing couple of lines. The previous code was:
```javascript
function mainLoop(canvas, ctx) {

    validation();
    movement();
    updateInformation();
    paintRect();
    boundaryChecking();
    collision();

    if (paused == false)
        draw();

    if (finished == true)
        location.reload(); 

}
```
I solved the issue by looking at how pause works. Whenever the game is paused it stops drawing, else it always calls the mainLoop function. Therefore it can't reach the end of code. In order to make it reachable, I did the following replacement, so that the new code looks like this:

```javascript
function mainLoop(canvas, ctx) {
    if (finished == true)
        location.reload(); 	

    if (paused == false)
        draw();

    validation();
    movement();
    updateInformation();
    paintRect();
    boundaryChecking();
    collision();	

}
```
So now, in this way, it first checks whether the game is finished or not. I tried this a few times, hopefully, I am not forgetting any other case.
